# Generated by Django 4.2.7 on 2023-11-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=255)),
                ('bot', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_actions',
                'managed': False,
            },
        ),
    ]
